### ISSUE TITLE
problems with new version

### ISSUE THREAD

**Issue by Lsvensson** [ecsalina/gtrends#3]
Hello Eric, 

The new version 0.2.0 gives me the following error term.
Do you have an idea what went wrong?
The previous version seems to run fine. 

King regards
Lars Svensson

C:\Python27\python.exe C:/Users/lay/PycharmProjects/test/test.py
Traceback (most recent call last):
  File "C:/Users/lay/PycharmProjects/test/test.py", line 2, in <module>
    import gtrends
  File "C:\Users\lay\AppData\Roaming\Python\Python27\site-packages\gtrends.py", line 12, in <module>
    from _login import Downloader
  File "C:\Users\lay\AppData\Roaming\Python\Python27\site-packages_login.py", line 1, in <module>
    import six
ImportError: No module named six

Process finished with exit code 1

**Comment by ecsalina** [comment]
Hmm. So I used the package 'six' to help with the different string representations between python 2 and python 3. I must not have included that with the other dependencies.

**Comment by ecsalina** [comment]
I just added six as a dependency and pushed a new version. It should now work fine.

**Comment by Lsvensson** [comment]
Perfect! Thank you!

**Comment by ecsalina** [comment]
Yes, you can check for multi-word terms. The space will get encoded as %20
automatically.

Good luck,
Eric
